apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: truststore-secret
  namespace: {{ .Values.release.project_name }}-{{ .Values.release.platform }}
spec:
  encryptedData:
    truststore.jks: {{ .Values.release.truststore }}
  template:
    metadata:
      creationTimestamp: null
      name: truststore-secret
      namespace: {{ .Values.release.project_name }}-{{ .Values.release.platform }}
