apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
  namespace: {{ .Values.release.project_name }}-{{ .Values.release.platform }}
data:
  db_host: {{ .Values.release.db_host }}
  application.properties: |-
    spring.jpa.hibernate.ddl-auto=update
    spring.datasource.url=jdbc:mysql://{{ .Values.release.db_host }}:3306/db_example
    spring.datasource.username={{ .Values.release.db_user }}
    spring.datasource.password={{ .Values.release.db_passwd }}
    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
