apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Chart.Name }}
  annotations:
    cert-utils-operator.redhat-cop.io/certs-from-secret: nginx.crt
spec:
  to:
    kind: Service
    name: {{ .Chart.Name }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
