apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Values.release.project_name }}-{{ .Values.release.platform }}
spec:
  encryptedData:
    db_passwd: {{ .Values.release.db_user }}
    db_user: {{ .Values.release.db_passwd }}
  template:
    metadata:
      creationTimestamp: null
      name: {{ .Chart.Name }}-secret
      namespace: {{ .Values.release.project_name }}-{{ .Values.release.platform }}

